import {test} from 'node:test';
import assert from 'node:assert/strict';
import {assignSquawk,updateAlerts,separation} from '../server/alerts.js';
import {createGame,tickGame,command} from '../server/game.js';
import {airports} from '../src/airports.js';
function pair(){const g=createGame(2,'medium'),a=g.aircraft[0],b=g.aircraft[1];g.aircraft=[a,b];for(const p of [a,b]){p.status='approach';p.altitude=1000;p.groundSpeed=0;p.heading=90;p.aircraftType='narrowbody';p.onFinal=false;}a.position=[0,0];b.position=[.2/airports.medium.nmPerUnit,0];return {g,a,b};}
test('normal squawks are unique octal codes and reserve emergency and radio codes',()=>{const g=createGame(2,'medium');g.aircraft[0].squawk='7700';const used=new Set(g.aircraft.map(p=>p.normalSquawk));for(let i=0;i<30;i++){const code=assignSquawk(g);assert.match(code,/^[0-7]{4}$/);assert.ok(!['7500','7600','7700'].includes(code));assert.ok(!used.has(code));used.add(code);g.aircraft.push({...g.aircraft[0],id:`test${i}`,normalSquawk:code,squawk:code});}});
test('prediction warns without points, actual separation loss scores once per incident',()=>{const {g,a,b}=pair();a.groundSpeed=140;b.heading=270;b.groundSpeed=140;updateAlerts(g,()=>{});assert.equal(g.alerts?.[0].severity,'warning');assert.equal(g.score,0);b.position=[.08/airports.medium.nmPerUnit,0];updateAlerts(g,()=>{});assert.equal(g.score,-100);updateAlerts(g,()=>{});assert.equal(g.score,-100);b.altitude=2000;updateAlerts(g,()=>{});assert.equal(g.alerts?.length,0);b.altitude=1000;updateAlerts(g,()=>{});assert.equal(g.score,-200);});
test('heavy wake spacing applies behind a heavy but not beside it',()=>{const {g,a,b}=pair();a.aircraftType='heavy';b.position=[-.15/airports.medium.nmPerUnit,0];updateAlerts(g,()=>{});assert.equal(g.alerts?.[0].kind,'wake');assert.equal(g.score,-100);b.position=[0,.15/airports.medium.nmPerUnit];updateAlerts(g,()=>{});assert.equal(g.alerts?.length,0);assert.ok(separation.wake>separation.horizontal);});
test('runway entry prediction warns and actual incursion is penalized once',()=>{const {g,a,b}=pair(),r=airports.medium.runways[0],scale=airports.medium.nmPerUnit;for(const p of [a,b]){p.status='taxi-out';p.altitude=0;}a.position=r.start;b.position=[r.start[0],r.start[1]+.022/scale];b.route=[b.position,r.start];b.heading=0;b.groundSpeed=18;updateAlerts(g,()=>{});assert.equal(g.alerts?.find(p=>p.kind==='incursion')?.severity,'warning');assert.equal(g.score,0);b.position=r.start;updateAlerts(g,()=>{});assert.equal(g.score,-75);updateAlerts(g,()=>{});assert.equal(g.score,-75);assert.equal(g.incursions,1);});
test('radio failure uses 7600, restores the normal code, and emergency uses 7700',()=>{const g=createGame(2,'medium'),a=g.aircraft[0];g.aircraft=[a];g.nextRadioLoss=1;g.nextWave=999;g.nextEmergency=999;const normal=a.normalSquawk;tickGame(g,1,()=>{});assert.equal(a.squawk,'7600');tickGame(g,25,()=>{});assert.equal(a.squawk,normal);assert.equal(a.radioLost,false);a.emergency=true;a.radioLost=true;a.radioRestoreAt=g.elapsed+1;tickGame(g,1,()=>{});assert.equal(a.squawk,'7700');});
test('a blocked occupied-runway clearance has no violation penalty',()=>{const g=createGame(2,'medium'),a=g.aircraft[0],b=g.aircraft[1];b.status='landing';b.runway=0;assert.ok(command(g,a.id,'land',0,a.revision,'Tower'));assert.equal(g.score,0);assert.equal(g.unsafe,0);});
