import {test} from 'node:test';import assert from 'node:assert/strict';
import {createGame,spawn,tickGame,command} from '../server/game.js';import {checkCrashes} from '../server/endless.js';import {patternGeometry} from '../src/flightPatterns.js';
function quiet(){const g=createGame(2,'medium',true);g.aircraft=[];g.nextWave=g.nextWeather=g.nextEmergency=g.nextRadioLoss=g.nextWind=99999;return g;}
test('endless run continues beyond seven minutes without a deadline',()=>{const g=quiet();tickGame(g,1200,()=>{});assert.equal(g.elapsed,1200);assert.equal(g.endReason,undefined);assert.ok(g.secondsLeft>0);});
test('emergency timer reaching zero ends and freezes an endless run',()=>{const g=quiet();spawn(g,'arrival',true);const p=g.aircraft[0];p.fuel=1;tickGame(g,10,()=>{});assert.match(g.endReason!,/emergency timer reached zero/);assert.equal(g.secondsLeft,0);const frozen=JSON.stringify(g);tickGame(g,20,()=>{});assert.equal(JSON.stringify(g),frozen);assert.match(command(g,p.id,'land',0,p.revision,'Test').error!,/Game over/);});
test('three failed approaches by the same aircraft end the run; Hold is not a failed approach',()=>{const g=quiet();spawn(g,'arrival');const p=g.aircraft[0];assert.equal(command(g,p.id,'hold',0,p.revision,'Test').changed,true);assert.equal(p.goArounds??0,0);for(let attempt=1;attempt<=3;attempt++){const r=patternGeometry(g,0,p.aircraftType);p.runway=p.approachRunway=0;p.status='approach';p.holdRequested=false;p.clearedToLand=false;p.patternPhase='final';p.patternLeg='final';p.patternLegs=['final'];p.onFinal=true;p.position=[r.start[0]-r.u[0]*.5,r.start[1]-r.u[1]*.5];p.heading=r.heading;p.altitude=40;tickGame(g,1,()=>{});assert.equal(p.goArounds,attempt);if(attempt<3)assert.equal(g.endReason,undefined);}assert.match(g.endReason!,/went around three times/);});
test('physical crashes count unique aircraft once and the third crashed aircraft ends play',()=>{const g=quiet();for(let i=0;i<3;i++){spawn(g,'arrival');const p=g.aircraft.at(-1)!;p.position=[0,0];p.altitude=1000;}checkCrashes(g,()=>{});assert.equal(g.crashes,3);assert.equal(g.aircraft.length,0);assert.match(g.endReason!,/Three aircraft crashed/);checkCrashes(g,()=>{});assert.equal(g.crashes,3);});
test('aircraft at different altitudes and separated warning distances do not count as crashes',()=>{const g=quiet();spawn(g,'arrival');spawn(g,'arrival');g.aircraft[0].position=[0,0];g.aircraft[0].altitude=1000;g.aircraft[1].position=[0,0];g.aircraft[1].altitude=2000;checkCrashes(g,()=>{});assert.equal(g.crashes,0);g.aircraft[1].position=[20,0];g.aircraft[1].altitude=1000;checkCrashes(g,()=>{});assert.equal(g.crashes,0);});
test('collision checks compare matching substeps and detect crossing trajectories',()=>{const g=quiet();spawn(g,'arrival');spawn(g,'arrival');for(const [i,p]of g.aircraft.entries()){p.altitude=1000;p.position=[i?20:-20,0];p.motionSamples=[{position:p.position,heading:90,altitude:1000},{position:[i?-20:20,0],heading:90,altitude:1000}];}checkCrashes(g,()=>{});assert.equal(g.crashes,2);assert.equal(g.endReason,undefined);checkCrashes(g,()=>{});assert.equal(g.crashes,2);});
