import {airports,runwayName} from './airports';
import type {Aircraft,GameState} from './protocol';
function fallback(p:Aircraft,i:number):[number,number]{return p.status==='gate'?[170+i*70,390]:[100+i*80,60];}
export function Radar({game,selected,onSelect}:{game:GameState;selected:string;onSelect:(id:string)=>void}){
 const config=airports[game.difficulty??'easy'];
 return <div className="radar-console"><div className="radar-topline"><span><i/> LIVE SURFACE RADAR</span><span>{config.code} / {config.runways.length} RUNWAYS</span></div><svg className="airport-map" viewBox="0 0 700 440" role="img" aria-label={`${config.name} (${config.code}) radar airport display. Select aircraft using the flight list below.`}>
 <defs><pattern id="radar-grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="#2e7861" strokeWidth=".5" opacity=".3"/></pattern><radialGradient id="radar-glow"><stop stopColor="#123c2a"/><stop offset="1" stopColor="#04120f"/></radialGradient><linearGradient id="radar-sweep"><stop stopColor="#6fffc0" stopOpacity="0"/><stop offset="1" stopColor="#6fffc0" stopOpacity=".12"/></linearGradient></defs>
 <rect width="700" height="440" fill="url(#radar-glow)"/><rect width="700" height="440" fill="url(#radar-grid)"/><g fill="none" stroke="#3f9771" strokeWidth=".65" opacity=".35">{[80,160,240,320].map(r=><circle key={r} cx="350" cy="210" r={r}/>)}<path d="M350 0V440M0 210H700" strokeDasharray="3 7"/></g><path className="radar-sweep" d="M350 210L700 120V210Z" fill="url(#radar-sweep)"/>
 <text x="18" y="22" className="map-label">{config.code} · SCHEMATIC / NOT TO SCALE</text><text x="680" y="22" textAnchor="end" className="map-label">TRUE NORTH ↑</text>
 {config.runways.map((r,i)=>{const closed=game.weather?.runway===i;const occupied=game.aircraft.some(p=>p.runway===i&&!p.onFinal&&['landing','takeoff','taxi-in'].includes(p.status));return <g key={i}><path d={`M${r.start[0]} ${r.start[1]}L${r.start[0]} 370H350V390`} stroke="#3c5f43" strokeWidth="7" fill="none"/><path d={`M${r.start[0]} ${r.start[1]}L${r.start[0]} 370H350V390`} stroke="#87996a" strokeWidth=".6" strokeDasharray="4 6" fill="none"/><path d={`M${r.start[0]} ${r.start[1]}L${r.end[0]} ${r.end[1]}`} stroke={closed?'#ff907f':occupied?'#ffc57a':'#79cdb0'} strokeWidth="12"/><path d={`M${r.start[0]} ${r.start[1]}L${r.end[0]} ${r.end[1]}`} stroke="#0e201b" strokeWidth="10"/><path d={`M${r.start[0]} ${r.start[1]}L${r.end[0]} ${r.end[1]}`} stroke="#acc8b8" strokeWidth=".7" strokeDasharray="10 8"/><text x={r.start[0]-7} y={r.start[1]-9} textAnchor="end" className="runway-label" style={{fontSize:12}}>{r.ends[0]}</text><text x={r.end[0]+7} y={r.end[1]+12} className="runway-label" style={{fontSize:12}}>{r.ends[1]}</text>{closed&&<text x={(r.start[0]+r.end[0])/2} y={(r.start[1]+r.end[1])/2-10} fill="#ff907f" fontSize="10">CLOSED</text>}{(game.wakeUntil?.[i]??0)>game.elapsed&&<text x={(r.start[0]+r.end[0])/2} y={(r.start[1]+r.end[1])/2+20} fill="#ffd58c" fontSize="10">WAKE {game.wakeUntil![i]-game.elapsed}s</text>}</g>})}
 <rect x="225" y="404" width="265" height="20" fill="#102a20" stroke="#47745c"/>{[1,2,3,4,5,6].map(n=><text key={n} x={230+n*36} y="418" textAnchor="middle" className="map-label">G{n}</text>)}<text x="350" y="365" className="map-label">TWY A · SIMPLIFIED</text>
 {game.aircraft.map((p,i)=>{const [x,y]=p.position??fallback(p,i);const color=p.emergency?'#ff907f':p.kind==='arrival'?'#8fffc2':'#ffd58c';const scale=p.aircraftType==='heavy'?1.15:p.aircraftType==='light'?.7:.9;return <g key={p.id} style={{transform:`translate(${x}px,${y}px)`,transition:'transform 1s linear'}} className="plane-marker" onClick={()=>onSelect(p.id)}><title>{p.callsign} · {p.aircraftType} · {p.status}</title><circle r="20" fill="transparent"/>{p.id===selected&&<circle r="20" fill="none" stroke="#d5ffea" strokeDasharray="5 4"/>}<g style={{transform:`rotate(${p.heading??0}deg) scale(${scale})`,transition:'transform 1s linear'}}><path d="M0-17C2-17 3-13 3-9V-3L16 5V9L3 5V12L8 16V19L0 16L-8 19V16L-3 12V5L-16 9V5L-3-3V-9C-3-13-2-17 0-17Z" fill={color} stroke="#052018" strokeWidth=".8"/><path d="M0-11V12" stroke="#062b21" strokeWidth="1"/></g><path d="M18-3h8l5-7" fill="none" stroke={color}/><rect x={x>490?-125:30} y="-27" width="120" height="32" fill="#051a13" fillOpacity=".88"/><text x={x>490?-120:35} y="-14" style={{fill:color,fontSize:10}}>{p.callsign}</text><text x={x>490?-120:35} y="0" className="radar-data">{p.aircraftType?.toUpperCase()} · GS {Math.round(p.groundSpeed??0)} KT</text></g>})}
 </svg><div className="radar-bottomline"><span><b className="arrival-key">◆</b> ARRIVAL <b className="departure-key">◆</b> DEPARTURE <b className="emergency-key">◆</b> EMERGENCY</span><span>{game.aircraft.length} TRACKS</span></div></div>;
}
