import {useState,useRef,useEffect} from 'react';
import {stands} from './ramps';
import {entryRoute,groundRoute,taxiName} from './routes';
import {airports,runwayName} from './airports';
import type {Aircraft,GameState} from './protocol';
function fallback(p:Aircraft,i:number):[number,number]{return p.status==='gate'?[170+i*70,390]:[100+i*80,60];}
export function Radar({game,selected,onSelect}:{game:GameState;selected:string;onSelect:(id:string)=>void}){
 const frame=useRef<HTMLDivElement>(null),svg=useRef<SVGSVGElement>(null),pointers=useRef(new Map<number,[number,number]>()),dragged=useRef(false),pressed=useRef<string|undefined>(undefined);
 const [view,setView]=useState({x:-150,y:-120,w:1000,h:700}),[mapError,setMapError]=useState('');
 const zoom=(factor:number)=>setView(v=>{const w=Math.max(200,Math.min(1000,v.w*factor)),h=w*.7;return {...v,x:v.x+(v.w-w)/2,y:v.y+(v.h-h)/2,w,h};});
 useEffect(()=>{const el=svg.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();zoom(e.deltaY>0?1.15:1/1.15);};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[]);
 const move=(e:React.PointerEvent<SVGSVGElement>)=>{const previous=pointers.current.get(e.pointerId);if(!previous)return;const current:[number,number]=[e.clientX,e.clientY];const rect=e.currentTarget.getBoundingClientRect();if(pointers.current.size===2){const other=[...pointers.current.entries()].find(([id])=>id!==e.pointerId)![1];const oldDistance=Math.hypot(previous[0]-other[0],previous[1]-other[1]),newDistance=Math.hypot(current[0]-other[0],current[1]-other[1]);if(oldDistance>5&&newDistance>5)zoom(oldDistance/newDistance);dragged.current=true;}else{const dx=current[0]-previous[0],dy=current[1]-previous[1];if(Math.abs(dx)+Math.abs(dy)>2)dragged.current=true;setView(v=>({...v,x:Math.max(-650,Math.min(850,v.x-dx*v.w/rect.width)),y:Math.max(-470,Math.min(580,v.y-dy*v.h/rect.height))}));}pointers.current.set(e.pointerId,current);};
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await frame.current?.closest('.airport-workspace')?.requestFullscreen();}catch{setMapError('Fullscreen unavailable in this browser. Use zoom and drag instead.');}};
 const config=airports[game.difficulty??'easy'];
 return <div className="radar-console" ref={frame}><div className="map-controls"><button aria-label="Zoom in" onClick={()=>zoom(1/1.25)}>+</button><button aria-label="Zoom out" onClick={()=>zoom(1.25)}>−</button><button onClick={()=>setView({x:-150,y:-120,w:1000,h:700})}>Recenter</button><button onClick={()=>void fullscreen()}>Fullscreen</button><small>Drag to pan · scroll or pinch to zoom</small></div>{mapError&&<p role="status">{mapError}</p>}<div className="radar-topline"><span><i/> LIVE SURFACE RADAR</span><span>{config.code} / {config.runways.length} RUNWAYS</span></div><svg className="airport-map" ref={svg} viewBox={`${view.x} ${view.y} ${view.w} ${view.h}`} onPointerDown={e=>{dragged.current=false;pressed.current=(e.target as Element).closest('[data-aircraft]')?.getAttribute('data-aircraft')??undefined;pointers.current.set(e.pointerId,[e.clientX,e.clientY]);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={move} onPointerUp={e=>{pointers.current.delete(e.pointerId);if(!dragged.current&&pressed.current)onSelect(pressed.current);pressed.current=undefined;}} onPointerCancel={e=>pointers.current.delete(e.pointerId)} role="img" aria-label={`${config.name} (${config.code}) radar airport display. Select aircraft using the flight list below.`}>
 <defs><pattern id="radar-grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M35 0H0V35" fill="none" stroke="#2e7861" strokeWidth=".5" opacity=".3"/></pattern><radialGradient id="radar-glow"><stop stopColor="#123c2a"/><stop offset="1" stopColor="#04120f"/></radialGradient><linearGradient id="radar-sweep"><stop stopColor="#6fffc0" stopOpacity="0"/><stop offset="1" stopColor="#6fffc0" stopOpacity=".12"/></linearGradient></defs>
 <rect x="-150" y="-120" width="1000" height="700" fill="url(#radar-glow)"/><rect x="-150" y="-120" width="1000" height="700" fill="url(#radar-grid)"/><g fill="none" stroke="#3f9771" strokeWidth=".65" opacity=".35">{[80,160,240,320].map(r=><circle key={r} cx="350" cy="210" r={r}/>)}<path d="M350 0V440M0 210H700" strokeDasharray="3 7"/></g><path className="radar-sweep" d="M350 210L700 120V210Z" fill="url(#radar-sweep)"/>
 <text x="18" y="22" className="map-label">{config.code} · SCHEMATIC / NOT TO SCALE</text><text x="680" y="22" textAnchor="end" className="map-label">TRUE NORTH ↑</text>
 {Array.from(new Set(stands[game.difficulty??'easy'].map(s=>s.terminal))).map(terminal=>{const group=stands[game.difficulty??'easy'].filter(s=>s.terminal===terminal),x=Math.min(...group.map(s=>s.position[0]))-24,y=Math.min(...group.map(s=>s.position[1]))-24,w=Math.max(...group.map(s=>s.position[0]))-x+24,h=Math.max(...group.map(s=>s.position[1]))-y+24;return <g key={terminal}><rect x={x} y={y} width={w} height={h} rx="12" fill="#153428" stroke="#527c65" opacity=".65"/><text x={x} y={y-8} className="map-label">{terminal} · APRON*</text></g>;})}
 {config.runways.map((r,i)=>{const closed=game.weather?.runway===i;const occupied=game.aircraft.some(p=>p.runway===i&&!p.onFinal&&['landing','takeoff','taxi-in'].includes(p.status));return <g key={i}>{[0,1].map(direction=>{const points=groundRoute({difficulty:game.difficulty??'easy',direction:direction as 0|1},i,[350,390],[350,390],false);return <polyline key={direction} points={points.map(p=>p.join(',')).join(' ')} stroke="#87996a" strokeWidth="3" fill="none"/>;})}<text x={(r.start[0]+r.end[0])/2} y={(r.start[1]+r.end[1])/2+30} className="map-label">TWY {taxiName(game.difficulty??'easy',i)}*</text><path d={`M${r.start[0]} ${r.start[1]}L${r.end[0]} ${r.end[1]}`} stroke={closed?'#ff907f':occupied?'#ffc57a':'#79cdb0'} strokeWidth="12"/><path d={`M${r.start[0]} ${r.start[1]}L${r.end[0]} ${r.end[1]}`} stroke="#0e201b" strokeWidth="10"/><path d={`M${r.start[0]} ${r.start[1]}L${r.end[0]} ${r.end[1]}`} stroke="#acc8b8" strokeWidth=".7" strokeDasharray="10 8"/><text x={r.start[0]-7} y={r.start[1]-9} textAnchor="end" className="runway-label" style={{fontSize:12}}>{r.ends[0]}</text><text x={r.end[0]+7} y={r.end[1]+12} className="runway-label" style={{fontSize:12}}>{r.ends[1]}</text>{closed&&<text x={(r.start[0]+r.end[0])/2} y={(r.start[1]+r.end[1])/2-10} fill="#ff907f" fontSize="10">CLOSED</text>}{(game.wakeUntil?.[i]??0)>game.elapsed&&<text x={(r.start[0]+r.end[0])/2} y={(r.start[1]+r.end[1])/2+20} fill="#ffd58c" fontSize="10">WAKE {game.wakeUntil![i]-game.elapsed}s</text>}</g>})}
 {stands[game.difficulty??'easy'].map(s=>{const occupant=game.aircraft.find(p=>p.standId===s.id);return <g key={s.id}><rect x={s.position[0]-18} y={s.position[1]-12} width="36" height="24" fill={occupant?'#65422b':'#183e37'} stroke={occupant?'#ffd58c':'#7ca88f'}/><text x={s.position[0]} y={s.position[1]+26} textAnchor="middle" className="map-label">{s.id}</text><text x={s.position[0]} y={s.position[1]-18} textAnchor="middle" className="map-label">{s.terminal}</text></g>;})}<text x="350" y="410" className="map-label">RAMPS / TAXIWAYS APPROXIMATE</text>
 {config.runways.map((_,r)=>{const inbound=entryRoute(game,r);return <g key={`in${r}`}><polyline points={inbound.points.map(p=>p.join(',')).join(' ')} fill="none" stroke="#53a389" strokeDasharray="3 7" opacity=".5"/><text x={inbound.points[0][0]+12} y={inbound.points[0][1]+12} className="map-label">{inbound.name}*</text></g>;})}
 {game.aircraft.filter(p=>p.status.startsWith('taxi')&&p.route).map(p=><polyline key={`route-${p.id}`} points={p.route!.map(q=>q.join(',')).join(' ')} fill="none" stroke="#b4bd71" strokeWidth="1.8" opacity=".7"/>)}
 {game.aircraft.map((p,i)=>{const [x,y]=p.position??fallback(p,i);const color=p.emergency?'#ff907f':p.kind==='arrival'?'#8fffc2':'#ffd58c';const scale=p.aircraftType==='heavy'?1.15:p.aircraftType==='light'?.7:.9;return <g key={p.id} style={{transform:`translate(${x}px,${y}px)`,transition:'transform 1s linear'}} className={`plane-marker ${game.alerts?.some(a=>a.aircraftIds.includes(p.id))?'conflict-track':''}`} data-aircraft={p.id}><title>{p.callsign} · {p.aircraftType} · {p.status}</title><circle r="20" fill="transparent"/>{p.id===selected&&<circle r="20" fill="none" stroke="#d5ffea" strokeDasharray="5 4"/>}<g style={{transform:`rotate(${p.heading??0}deg) scale(${scale})`,transition:'transform 1s linear'}}><path d="M0-17C2-17 3-13 3-9V-3L16 5V9L3 5V12L8 16V19L0 16L-8 19V16L-3 12V5L-16 9V5L-3-3V-9C-3-13-2-17 0-17Z" fill={color} stroke="#052018" strokeWidth=".8"/><path d="M0-11V12" stroke="#062b21" strokeWidth="1"/></g><path d="M18-3h8l5-7" fill="none" stroke={color}/><rect x={x>490?-125:30} y="-27" width="120" height="47" fill="#051a13" fillOpacity=".88"/><text x={x>490?-120:35} y="-14" style={{fill:color,fontSize:10}}>{p.callsign}</text><text x={x>490?-120:35} y="0" className="radar-data">{p.aircraftType?.toUpperCase()} · GS {Math.round(p.groundSpeed??0)} KT</text><text x={x>490?-120:35} y="13" className="radar-data">ALT {Math.round((p.altitude??0)+config.elevationFt)} · SQ {p.squawk??'----'}</text></g>})}
 </svg><svg className="overview-map" viewBox="-150 -120 1000 700" role="img" aria-label="Overview map with current view rectangle"><rect x="-150" y="-120" width="1000" height="700" fill="#061811"/>{config.runways.map((r,i)=><line key={i} x1={r.start[0]} y1={r.start[1]} x2={r.end[0]} y2={r.end[1]} stroke="#7ca88f" strokeWidth="10"/>)}{game.aircraft.map(p=><circle key={p.id} cx={p.position?.[0]} cy={p.position?.[1]} r="7" fill={p.id===selected?'#ffd58c':'#8fffc2'}/>)}<rect x={view.x} y={view.y} width={view.w} height={view.h} fill="none" stroke="#ffd58c" strokeWidth="8"/></svg><div className="radar-bottomline"><span><b className="arrival-key">◆</b> ARRIVAL <b className="departure-key">◆</b> DEPARTURE <b className="emergency-key">◆</b> EMERGENCY</span><span>{game.aircraft.length} TRACKS</span></div></div>;
}
