import {airports,runwayEnds,type Difficulty,type Point} from './airports.js';
export const airspace={left:-130,right:830,top:-100,bottom:560};
// Names verified against FAA PRC/ORD pages, PHX standardized taxi routes, and LAWA E16/E18 advisory.
// Coordinates, connectors, stands and inbound/outbound fixes are schematic game geometry.
export const groundNames:Record<Difficulty,string[]>={easy:['A','B','D'],medium:['E','F','C'],hard:['E','E'],expert:['A']};
export function taxiName(d:Difficulty,r:number){return groundNames[d][r%groundNames[d].length];}
export function boundaryPoint(from:Point,toward:Point):Point{const dx=toward[0]-from[0],dy=toward[1]-from[1];const candidates=[dx>0?(airspace.right-from[0])/dx:dx<0?(airspace.left-from[0])/dx:Infinity,dy>0?(airspace.bottom-from[1])/dy:dy<0?(airspace.top-from[1])/dy:Infinity].filter(t=>t>=0);const t=Math.min(...candidates);return [from[0]+dx*t,from[1]+dy*t];}
export function entryRoute(game:{difficulty?:Difficulty;direction?:0|1},r:number){const [start,end]=runwayEnds(game,r),boundary=boundaryPoint(start,[start[0]*2-end[0],start[1]*2-end[1]]);const d=Math.hypot(end[0]-start[0],end[1]-start[1]);const final:Point=[start[0]+(start[0]-end[0])*15/d,start[1]+(start[1]-end[1])*15/d];return {name:`IN-${r+1}${game.direction?'B':'A'}`,points:[boundary,final] as Point[]};}
export function exitPoint(game:{difficulty?:Difficulty;direction?:0|1},r:number){const [start,end]=runwayEnds(game,r);return boundaryPoint(end,[end[0]*2-start[0],end[1]*2-start[1]]);}
export function groundRoute(game:{difficulty?:Difficulty;direction?:0|1},r:number,gate:Point,from:Point,arrival:boolean,ahead=0):Point[]{const [start,end]=runwayEnds(game,r),d=Math.hypot(end[0]-start[0],end[1]-start[1]),normal:Point=[-(end[1]-start[1])/d,(end[0]-start[0])/d];const midpoint:Point=[(start[0]+end[0])/2,(start[1]+end[1])/2];const side=(gate[0]-midpoint[0])*normal[0]+(gate[1]-midpoint[1])*normal[1]>=0?1:-1;const offset=Math.max(30,.08/airports[game.difficulty??'easy'].nmPerUnit);const shifted=(p:Point):Point=>[p[0]+normal[0]*side*offset,p[1]+normal[1]*side*offset];if(arrival){const projection=(from[0]-start[0])*(end[0]-start[0])/d+(from[1]-start[1])*(end[1]-start[1])/d;const along:Point=[start[0]+(end[0]-start[0])*Math.min(d*.9,projection+35)/d,start[1]+(end[1]-start[1])*Math.min(d*.9,projection+35)/d];const gateProjection=Math.max(0,Math.min(d,((gate[0]-start[0])*(end[0]-start[0])+(gate[1]-start[1])*(end[1]-start[1]))/d));const nearGate:Point=[start[0]+(end[0]-start[0])*gateProjection/d,start[1]+(end[1]-start[1])*gateProjection/d];return [from,along,shifted(along),shifted(nearGate),gate];}const hold=shifted([start[0]+(end[0]-start[0])*Math.min(d*.25,10+ahead*12)/d,start[1]+(end[1]-start[1])*Math.min(d*.25,10+ahead*12)/d]);return [from,[gate[0],hold[1]],hold];}
